"""
Django settings for Solisart_SAV project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os

import pyodbc

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v!t0pw34)pdu6&rda86ll_c8c9y0e1s3d^y+5%jz5o)-52(4!3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["127.0.0.1","localhost", "192.168.10.250", "solistools.fr"]

INTERNAL_IPS = (
    '127.0.0.1',
)

# Application definition    

INSTALLED_APPS = [
    'daphne',
    'sav',
    'heraklesinfo',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'crispy_forms',
    "crispy_bootstrap5",
    'django_celery_beat',
    'django_celery_results',
    'corsheaders',
    'rest_framework',
]



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'Solisart_SAV.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ]
        },
    },
]

WSGI_APPLICATION = 'Solisart_SAV.wsgi.application'



# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
         'NAME': 'SAV',
         'USER': 'postgres',
         # 'PASSWORD': 'G2poilOQ!',
         # 'HOST': '127.0.0.1',
          'PASSWORD': 'SolisArt',
          'HOST': '192.168.10.250',
         'PORT': '5432',
    },
    'herakles':{
        'ENGINE': 'mssql',
         'NAME': 'DQE',
         'USER': 'sa',
          'PASSWORD': 'Her@kles',
          'HOST': '192.168.10.13\HERAKLES',
         'PORT': '',
        "OPTIONS": {
            "driver": "ODBC Driver 17 for SQL Server",
            'unicode_results': True
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_AGE = 60 * 60 * 24
SESSION_SAVE_EVERY_REQUEST = True

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Europe/Paris'

USE_I18N = False

USE_TZ = True

LOGIN_URL = '/login'
LOGIN_REDIRECT_URL = '/'

# AUTHENTICATION_BACKENDS = ['sav.backend.EmailBackend']

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'freddy.solisart@gmail.com'
EMAIL_HOST_PASSWORD = 'tmmacqqpahpvzrpi'
DEFAULT_FROM_EMAIL ='sav@solisart.fr'

# DEFAULT_FROM_EMAIL = 'freddy.dubouchet@solisart.fr'
# SERVER_EMAIL = 'freddy.dubouchet@solisart.fr'
# EMAIL_USE_TLS = True
# EMAIL_HOST = 'smtp.office365.com'
# EMAIL_PORT = 587
# EMAIL_HOST_USER = 'freddy.dubouchet@solisart.fr'
# EMAIL_HOST_PASSWORD = 'flgghhbdtjlcckmg' #il faut créer un mot de passe pour application lmzoieaojsoquowx

DATETIME_INPUT_FORMATS = ('%d-%m-%Y %H:%M')

'''
aller sur https://myaccount.microsoft.com/
se connecter avec son compte (support@apixanalytics.com) serait le mieux
information de sécurité (Mettre à jour les informations)
Ajouter une méthode de connexion (méthode = mot de passe d'application)
Récupérer le mot de passe et l'affecter à EMAIL_HOST_PASSWORD
'''

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR.parent, 'static')

MEDIA_URL = '/media/'
MEDIA_ROOT = '/home/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Parameter for crispy
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = "bootstrap5"

# Celery settings
broker_url = 'redis://localhost:6379'
result_backend = 'redis://localhost:6379'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Europe/Paris'
CELERY_ENABLE_UTC = True
CELERY_RESULT_BACKEND = 'django-db'
CELERY_CACHE_BACKEND = 'django-cache'

#to priorise celery's tasks 
CELERY_ACKS_LATE = True
CELERYD_PREFETCH_MULTIPLIER = 1


# this allows you to schedule items in the Django admin.
# CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers.DatabaseScheduler'
#

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}

INSTALLED_APPS.append('channels')
ASGI_APPLICATION = 'Solisart_SAV.asgi.application'


GRAPH_MODELS ={
'all_applications': True,
'graph_models': True,
}

#for React js
# suite tuto https://stacklima.com/integration-de-django-avec-reactjs-a-l-aide-de-django-rest-framework/
CORS_ORIGIN_WHITELIST = (
    'http://localhost:3000',
)

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}

