# Generated by Django 4.1 on 2023-07-07 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heraklesinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='c7001phases',
            options={'managed': False, 'ordering': ('-codephase',)},
        ),
    ]
