# Generated by Django 4.1 on 2022-09-01 06:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sav', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profil',
            new_name='profil_user',
        ),
    ]
