# Generated by Django 4.1 on 2022-09-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0002_rename_profil_profil_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribut_valeur',
            name='valeur',
            field=models.CharField(max_length=500, verbose_name='Valeur'),
        ),
    ]
