# Generated by Django 4.1 on 2022-09-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0003_alter_attribut_valeur_valeur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribut_valeur',
            name='valeur',
            field=models.TextField(max_length=1500, verbose_name='Valeur'),
        ),
    ]
