# Generated by Django 4.1 on 2022-09-05 13:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sav', '0004_alter_attribut_valeur_valeur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fichiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=255)),
                ('fichier', models.FileField(upload_to='files/')),
                ('téléchargé_a', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='probleme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.IntegerField(choices=[(0, 'Connexion'), (1, 'Electronique'), (2, 'Fluidique')], default=0, verbose_name='Catégorie')),
                ('sous_categorie', models.CharField(max_length=100, verbose_name='Sous catégorie')),
            ],
        ),
        migrations.AlterModelOptions(
            name='installation',
            options={'ordering': ['idsa']},
        ),
        migrations.AddField(
            model_name='installation',
            name='schema_installation',
            field=models.FileField(blank=True, null=True, upload_to='Schema_installation/', verbose_name='Schéma'),
        ),
        migrations.AddField(
            model_name='profil_user',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='profil_user',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='installation',
            name='port_tcp_wan',
            field=models.IntegerField(blank=True, null=True, verbose_name='Port TCP WAN'),
        ),
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forme', models.IntegerField(choices=[(0, 'téléphone'), (1, 'Email'), (2, 'Physiquement')], default=0, verbose_name='Forme')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='Détail')),
                ('fichier', models.ManyToManyField(blank=True, null=True, to='sav.fichiers', verbose_name='fichiers')),
                ('probleme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sav.probleme', verbose_name='Type de probleme')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='contact')),
            ],
        ),
        migrations.CreateModel(
            name='evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now, help_text='Date et heure de événement', verbose_name='Date')),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sav.installation', verbose_name='Installation')),
                ('technicien_sav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='technicien sav')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sav.ticket', verbose_name='Installation')),
            ],
        ),
    ]
