# Generated by Django 4.1 on 2022-09-05 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0005_fichiers_probleme_alter_installation_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fichiers',
            old_name='téléchargé_a',
            new_name='telecharge_a',
        ),
    ]
