# Generated by Django 4.1 on 2022-09-09 07:25

from django.db import migrations, models
import django.db.models.deletion
import sav.models


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0006_rename_téléchargé_a_fichiers_telecharge_a'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='probleme',
            options={'ordering': ['categorie', 'sous_categorie']},
        ),
        migrations.AddField(
            model_name='ticket',
            name='etat',
            field=models.IntegerField(choices=[(0, 'Ouverture'), (1, 'En cours'), (2, 'Clôturé')], default=0, verbose_name='Etat'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sav.ticket', verbose_name='Ticket'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='schema_installation',
            field=models.FileField(blank=True, null=True, upload_to='Schema_installation/', validators=[sav.models.validate_file_extension_pdf], verbose_name='Schéma'),
        ),
    ]
