# Generated by Django 4.1 on 2022-09-12 08:11

from django.db import migrations, models
import django.db.models.deletion
import sav.models


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0007_alter_probleme_options_ticket_etat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='donnee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idsa', models.CharField(max_length=50, verbose_name='id solisart')),
                ('nom_carte', models.CharField(max_length=50, verbose_name='Nom carte')),
                ('description', models.CharField(max_length=100, verbose_name='Nom carte')),
            ],
        ),
        migrations.AlterField(
            model_name='installation',
            name='schema_installation',
            field=models.FileField(blank=True, null=True, upload_to='Schema_installation/', validators=[sav.models.validate_file_extension_pdf], verbose_name='Schéma de principe'),
        ),
        migrations.CreateModel(
            name='historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure', models.DateTimeField(verbose_name='Date et heure')),
                ('valeur', models.CharField(max_length=50, verbose_name='Valeur')),
                ('donnee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sav.donnee', verbose_name='Donnée')),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sav.installation', verbose_name='Installation')),
            ],
        ),
    ]
