# Generated by Django 4.1 on 2022-09-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0008_donnee_alter_installation_schema_installation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historique',
            name='heure',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date et heure'),
        ),
    ]
