# Generated by Django 4.1 on 2022-09-15 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0009_alter_historique_heure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='ticket',
        ),
        migrations.AddField(
            model_name='ticket',
            name='evenement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sav.evenement', verbose_name='Ticket'),
        ),
        migrations.AlterField(
            model_name='donnee',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Description'),
        ),
    ]
