# Generated by Django 4.1 on 2022-10-03 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sav', '0010_remove_evenement_ticket_ticket_evenement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil_user',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entreprise', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profil_user',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
