# Generated by Django 4.1 on 2022-10-20 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sav', '0011_profil_user_entreprise_alter_profil_user_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='cause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.IntegerField(choices=[(0, 'Connexion'), (1, 'Electronique'), (2, 'Module'), (3, 'Hors Module'), (4, 'Ballon'), (5, 'Capteur'), (6, 'Problème en Production')], default=0, verbose_name='Catégorie')),
                ('sous_categorie', models.CharField(max_length=100, verbose_name='Sous catégorie')),
            ],
        ),
        migrations.AlterModelOptions(
            name='profil_user',
            options={'ordering': ['idsa']},
        ),
        migrations.AlterField(
            model_name='probleme',
            name='categorie',
            field=models.IntegerField(choices=[(0, 'Connexion'), (1, 'Problème technique'), (2, 'Pièces SAV'), (3, 'Aide au paramétrage'), (4, 'Information diverse'), (5, 'Demande de prestation'), (6, 'Erreur de production')], default=0, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='profil_user',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profil_user', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='etat',
            field=models.IntegerField(choices=[(0, 'Ouverture'), (1, 'En cours'), (2, 'A rappeler'), (3, 'Clôturé')], default=0, verbose_name='Etat'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='evenement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sav.evenement', verbose_name='Evenement'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fichier',
            field=models.ManyToManyField(blank=True, null=True, to='sav.fichiers', verbose_name='Fichiers'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='probleme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sav.probleme', verbose_name='Symptômes'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Contact'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='cause',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sav.cause', verbose_name='Causes'),
        ),
    ]
