# Generated by Django 4.1 on 2022-10-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0012_cause_alter_profil_user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cause',
            options={'ordering': ['categorie', 'sous_categorie']},
        ),
        migrations.AlterField(
            model_name='cause',
            name='categorie',
            field=models.IntegerField(choices=[(0, 'Connexion'), (1, 'Electronique'), (2, 'Module'), (3, 'Appoint'), (4, 'Ballon'), (5, 'Capteur'), (6, 'Problème en Production'), (7, 'Utilisation')], default=0, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='adresse_ip_wan',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Adresse IP WAN'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='forme',
            field=models.IntegerField(choices=[(0, 'Téléphone'), (1, 'Email'), (2, 'Physiquement')], default=0, verbose_name='Forme'),
        ),
    ]
