# Generated by Django 4.1 on 2022-11-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0013_alter_cause_options_alter_cause_categorie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probleme',
            name='categorie',
            field=models.IntegerField(choices=[(0, 'Pas de Connexion'), (1, 'Problème technique'), (2, 'Pièces SAV'), (3, 'Aide au paramétrage'), (4, 'Information diverse'), (5, 'Demande de prestation'), (6, 'Erreur de production')], default=0, verbose_name='Catégorie'),
        ),
    ]
