# Generated by Django 4.1 on 2022-12-08 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0014_alter_probleme_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='MES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='Détail')),
                ('evenement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sav.evenement', verbose_name='Evenement')),
                ('fichier', models.ManyToManyField(blank=True, null=True, to='sav.fichiers', verbose_name='Fichiers')),
            ],
        ),
    ]
