# Generated by Django 4.1 on 2022-12-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0015_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil_user',
            name='departement',
            field=models.JSONField(blank=True, null=True, verbose_name='liste de département'),
        ),
        migrations.AlterField(
            model_name='fichiers',
            name='fichier',
            field=models.FileField(max_length=300, upload_to='files/'),
        ),
    ]
