# Generated by Django 4.1 on 2023-01-24 13:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import sav.models


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0017_profil_user_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dossier', models.IntegerField(choices=[(0, 'Installation'), (1, 'Dépannage'), (2, 'Interne'), (3, 'Logiciel')], default=0, verbose_name='Dossier')),
                ('titre', models.TextField(max_length=100, verbose_name='Titre de la procédure')),
            ],
        ),
        migrations.AlterField(
            model_name='profil_user',
            name='departement',
            field=models.JSONField(blank=True, help_text='la liste doit être du format:["XX", "XX", ...], mettre 100 pour la Belgique', null=True, verbose_name='liste de département'),
        ),
        migrations.CreateModel(
            name='documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to=sav.models.group_based_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf', 'mp4', 'mpeg', 'avi', 'wav'])], verbose_name='Fichier')),
                ('version', models.CharField(max_length=10, verbose_name='Version du document')),
                ('date', models.DateField(verbose_name='Date de mise en application')),
                ('etat', models.IntegerField(choices=[(0, 'Valide'), (1, 'Obsolète'), (2, 'A refondre')], default=0, verbose_name='Etat du document')),
                ('commentaire', models.TextField(max_length=500, verbose_name='Commentaire évolution')),
                ('a_ameliorer', models.TextField(max_length=500, verbose_name='Point à améliorer')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sav.classification', verbose_name='Classification du document')),
            ],
        ),
    ]
