# Generated by Django 4.1 on 2023-02-24 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0019_classification_categorie_classification_sous_dossier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sav.classification', verbose_name='Classification du document'),
        ),
    ]
