# Generated by Django 4.1 on 2023-05-26 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0020_alter_documentation_classification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classification',
            options={'ordering': ['categorie', 'dossier', 'titre']},
        ),
        migrations.AlterModelOptions(
            name='documentation',
            options={'ordering': ['date']},
        ),
    ]
