# Generated by Django 4.1 on 2023-06-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0021_alter_classification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil_user',
            name='mailOcommercial',
            field=models.BooleanField(default=True, verbose_name='Recevoir rapport des tickets hebdomadaires '),
        ),
    ]
