# Generated by Django 4.1 on 2023-06-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0022_profil_user_mailocommercial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BL_herakles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BL', models.CharField(max_length=25, verbose_name='BL')),
            ],
        ),
        migrations.CreateModel(
            name='devis_herakles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devis', models.CharField(max_length=25, verbose_name='Devis')),
            ],
        ),
        migrations.AlterField(
            model_name='probleme',
            name='categorie',
            field=models.IntegerField(choices=[(0, 'Pas de Connexion'), (1, 'Problème technique'), (2, 'Pièces SAV'), (3, 'Aide au paramétrage'), (4, 'Information diverse'), (5, 'Demande de prestation'), (6, 'Erreur de production'), (7, 'Préventif')], default=0, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='forme',
            field=models.IntegerField(choices=[(0, 'Téléphone'), (1, 'Email'), (2, 'Physiquement'), (3, 'Aucun')], default=0, verbose_name='Forme'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='BL',
            field=models.ManyToManyField(blank=True, null=True, to='sav.bl_herakles'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='devis',
            field=models.ManyToManyField(blank=True, null=True, to='sav.devis_herakles'),
        ),
    ]
