# Generated by Django 4.1 on 2023-06-26 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0023_bl_herakles_devis_herakles_alter_probleme_categorie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='client_herakles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code_Client', models.CharField(help_text='Appuyer sur Ctrl pour sélectionner plusieurs Client', max_length=25, verbose_name='Code Client')),
                ('Nom', models.CharField(help_text='Appuyer sur Ctrl pour sélectionner plusieurs Client', max_length=60, verbose_name='Nom')),
            ],
            options={
                'ordering': ('Code_Client',),
            },
        ),
        migrations.AlterModelOptions(
            name='bl_herakles',
            options={'ordering': ('-BL',)},
        ),
        migrations.AlterModelOptions(
            name='devis_herakles',
            options={'ordering': ('-devis',)},
        ),
        migrations.AlterField(
            model_name='bl_herakles',
            name='BL',
            field=models.CharField(help_text='Appuyer sur Ctrl pour sélectionner plusieurs BL', max_length=25, verbose_name='BL'),
        ),
        migrations.AlterField(
            model_name='devis_herakles',
            name='devis',
            field=models.CharField(help_text='Appuyer sur Ctrl pour sélectionner plusieurs devis', max_length=25, verbose_name='Devis'),
        ),
        migrations.AddField(
            model_name='profil_user',
            name='Client_herakles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sav.client_herakles'),
        ),
    ]
