# Generated by Django 4.1 on 2023-06-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0025_alter_client_herakles_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='probleme',
            name='causes',
            field=models.ManyToManyField(blank=True, null=True, to='sav.cause'),
        ),
    ]
