# Generated by Django 4.1 on 2023-06-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0026_probleme_causes'),
    ]

    operations = [
        migrations.CreateModel(
            name='solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.CharField(max_length=100, verbose_name='Solution')),
            ],
        ),
        migrations.AlterField(
            model_name='probleme',
            name='causes',
            field=models.ManyToManyField(blank=True, null=True, to='sav.cause', verbose_name='Causes possible'),
        ),
        migrations.AddField(
            model_name='cause',
            name='solution',
            field=models.ManyToManyField(blank=True, null=True, to='sav.solution', verbose_name='Solutions'),
        ),
    ]
