# Generated by Django 4.1 on 2023-07-07 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0027_solution_alter_probleme_causes_cause_solution'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solution',
            options={'ordering': ['solution']},
        ),
    ]
