# Generated by Django 4.1 on 2023-08-01 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0027_solution_alter_probleme_causes_cause_solution'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solution',
            options={'ordering': ['solution']},
        ),
        migrations.AlterField(
            model_name='evenement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 1, 15, 29, 15, 577955), help_text='Date et heure de événement', verbose_name='Date'),
        ),
    ]
