# Generated by Django 4.1 on 2023-08-01 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0028_alter_solution_options_alter_evenement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 1, 15, 38, 2, 816466), help_text='Date et heure de événement', verbose_name='Date'),
        ),
    ]
