# Generated by Django 4.1 on 2023-08-04 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0031_capteur_module_alter_evenement_date_cl_herakles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capteur',
            name='type',
            field=models.CharField(max_length=50, verbose_name='Capteur'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 4, 15, 4, 49, 813550), help_text='Date et heure de événement', verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='module',
            name='type',
            field=models.CharField(max_length=50, verbose_name='Type'),
        ),
    ]
