# Generated by Django 4.1 on 2023-08-04 13:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0032_alter_capteur_type_alter_evenement_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='transporteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Transporteur')),
            ],
        ),
        migrations.AlterField(
            model_name='evenement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 4, 15, 13, 7, 552575), help_text='Date et heure de événement', verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='cl_herakles',
            name='transporteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sav.transporteur'),
        ),
    ]
