# Generated by Django 4.1 on 2023-08-07 13:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0034_alter_cl_herakles_cl_alter_cl_herakles_date_montage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cl_herakles',
            name='BL',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sav.bl_herakles'),
        ),
        migrations.AddField(
            model_name='cl_herakles',
            name='capteur_nbre',
            field=models.IntegerField(default=0, verbose_name='Nombre de capteur'),
        ),
        migrations.AlterField(
            model_name='cl_herakles',
            name='date_livraison',
            field=models.DateField(blank=True, help_text='Date réelle', null=True, verbose_name='Date de livraison'),
        ),
        migrations.AlterField(
            model_name='cl_herakles',
            name='date_montage',
            field=models.DateField(blank=True, help_text='Date réelle', null=True, verbose_name='Date de montage'),
        ),
        migrations.AlterField(
            model_name='cl_herakles',
            name='date_montage_prevu',
            field=models.DateField(blank=True, help_text='2 semaine avant livraison prévu', null=True, verbose_name='Date de montage prévue'),
        ),
        migrations.AlterField(
            model_name='cl_herakles',
            name='date_reglement',
            field=models.DateField(blank=True, null=True, verbose_name='Date de réglement réelle'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 7, 15, 19, 13, 653291), help_text='Date et heure de événement', verbose_name='Date'),
        ),
    ]
