# Generated by Django 4.1 on 2023-08-09 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0035_cl_herakles_bl_cl_herakles_capteur_nbre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cl_herakles',
            name='date_ballon',
            field=models.DateField(blank=True, help_text='Date réelle', null=True, verbose_name='Date Ballon prêt'),
        ),
        migrations.AddField(
            model_name='cl_herakles',
            name='date_ballon_prevu',
            field=models.DateField(blank=True, help_text='Date prévisionnelle', null=True, verbose_name='Date prévu de préparation des ballons'),
        ),
        migrations.AddField(
            model_name='cl_herakles',
            name='date_capteur',
            field=models.DateField(blank=True, help_text='Date réelle', null=True, verbose_name='Date Capteur prêt'),
        ),
        migrations.AddField(
            model_name='cl_herakles',
            name='date_capteur_prevu',
            field=models.DateField(blank=True, help_text='Date prévisionnelle', null=True, verbose_name='Date prévu de préparation des capteurs'),
        ),
        migrations.AddField(
            model_name='cl_herakles',
            name='date_prepa',
            field=models.DateField(blank=True, help_text='Date réelle', null=True, verbose_name='Date Préparation de commande prête'),
        ),
        migrations.AddField(
            model_name='cl_herakles',
            name='date_prepa_carte',
            field=models.DateField(blank=True, help_text='Date réelle', null=True, verbose_name='Date Carte prête'),
        ),
        migrations.AddField(
            model_name='cl_herakles',
            name='date_prepa_carte_prevu',
            field=models.DateField(blank=True, help_text='Date prévisionnelle', null=True, verbose_name='Date prévu pour paramétrer la carte'),
        ),
        migrations.AddField(
            model_name='cl_herakles',
            name='date_prepa_prevu',
            field=models.DateField(blank=True, help_text='Date prévisionnelle', null=True, verbose_name='Date prévu de préparation de la commande'),
        ),
        migrations.AlterField(
            model_name='cl_herakles',
            name='CL',
            field=models.CharField(default='default', max_length=25, verbose_name='CL'),
        ),
        migrations.AlterField(
            model_name='cl_herakles',
            name='date_livraison_prevu',
            field=models.DateField(blank=True, help_text='Définit sur Héraklès', null=True, verbose_name='Date de récetion prévue'),
        ),
        migrations.AlterField(
            model_name='cl_herakles',
            name='date_montage_prevu',
            field=models.DateField(blank=True, help_text='2 semaines avant livraison prévu', null=True, verbose_name='Date de montage prévue'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 15, 49, 21, 577034), help_text='Date et heure de événement', verbose_name='Date'),
        ),
    ]
