# Generated by Django 4.1 on 2023-08-10 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0036_cl_herakles_date_ballon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cl_herakles',
            name='ballon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ballon'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 10, 11, 55, 13, 871788), help_text='Date et heure de événement', verbose_name='Date'),
        ),
    ]
