# Generated by Django 4.1 on 2023-08-17 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0037_cl_herakles_ballon_alter_evenement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cl_herakles',
            name='prix_transport',
            field=models.FloatField(default=0, verbose_name='Tarif réel du transport'),
        ),
        migrations.AlterField(
            model_name='cl_herakles',
            name='date_ballon_prevu',
            field=models.DateField(blank=True, help_text='Date prévisionnelle', null=True, verbose_name='Date prévu de prépades ballons'),
        ),
        migrations.AlterField(
            model_name='cl_herakles',
            name='date_capteur_prevu',
            field=models.DateField(blank=True, help_text='Date prévisionnelle', null=True, verbose_name='Date prévu de prépa capteurs'),
        ),
        migrations.AlterField(
            model_name='cl_herakles',
            name='date_livraison_prevu',
            field=models.DateField(blank=True, help_text='Définit sur Héraklès', null=True, verbose_name='Date de réception prévue'),
        ),
        migrations.AlterField(
            model_name='cl_herakles',
            name='date_montage_prevu',
            field=models.DateField(blank=True, help_text='2 semaines avant livraison prévu', null=True, verbose_name='Date prévue de montage '),
        ),
        migrations.AlterField(
            model_name='cl_herakles',
            name='date_prepa',
            field=models.DateField(blank=True, help_text='Date réelle', null=True, verbose_name='Date Prépa CL prête'),
        ),
        migrations.AlterField(
            model_name='cl_herakles',
            name='date_prepa_carte_prevu',
            field=models.DateField(blank=True, help_text='Date prévisionnelle', null=True, verbose_name='Date prévu pour la carte'),
        ),
        migrations.AlterField(
            model_name='cl_herakles',
            name='date_prepa_prevu',
            field=models.DateField(blank=True, help_text='Date prévisionnelle', null=True, verbose_name='Date prévu de prépa du CL'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 17, 9, 28, 52, 124768), help_text='Date et heure de événement', verbose_name='Date'),
        ),
    ]
