# Generated by Django 4.1 on 2023-09-12 14:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0039_cl_herakles_date_last_update_information_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cl_herakles',
            name='fichier',
            field=models.ManyToManyField(blank=True, null=True, to='sav.fichiers', verbose_name='Fichiers'),
        ),
        migrations.AddField(
            model_name='cl_herakles',
            name='installation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sav.installation', verbose_name='installation'),
        ),
        migrations.AlterField(
            model_name='cl_herakles',
            name='date_last_update_information',
            field=models.DateField(default=datetime.datetime(2023, 9, 12, 14, 2, 17, 782794, tzinfo=datetime.timezone.utc), verbose_name='Date de dernière modif commentaire'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 12, 16, 2, 17, 777950), help_text='Date et heure de événement', verbose_name='Date'),
        ),
    ]
