# Generated by Django 4.1 on 2023-09-25 14:26

import datetime
from django.db import migrations, models
import sav.models


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0040_cl_herakles_fichier_cl_herakles_installation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil_user',
            name='solisgraph_json',
            field=models.JSONField(default=sav.models.json_solisgraph_default, verbose_name='json Solisgraph'),
        ),
        migrations.AlterField(
            model_name='cl_herakles',
            name='date_ballon_prevu',
            field=models.DateField(blank=True, help_text='Date prévisionnelle', null=True, verbose_name='Date prévu de prépa des ballons'),
        ),
        migrations.AlterField(
            model_name='cl_herakles',
            name='date_last_update_information',
            field=models.DateField(default=datetime.datetime(2023, 9, 25, 14, 26, 28, 105926, tzinfo=datetime.timezone.utc), verbose_name='Date de dernière modif commentaire'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 25, 16, 26, 28, 101068), help_text='Date et heure de événement', verbose_name='Date'),
        ),
    ]
