# Generated by Django 4.1 on 2023-09-25 14:38

import datetime
from django.db import migrations, models
import sav.models


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0041_profil_user_solisgraph_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil_user',
            name='solisgraph_json_schema',
            field=models.JSONField(default=sav.models.json_solisgraph_schema_default, verbose_name='json Solisgraph schema'),
        ),
        migrations.AlterField(
            model_name='cl_herakles',
            name='date_last_update_information',
            field=models.DateField(default=datetime.datetime(2023, 9, 25, 14, 38, 15, 387702, tzinfo=datetime.timezone.utc), verbose_name='Date de dernière modif commentaire'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 25, 16, 38, 15, 382576), help_text='Date et heure de événement', verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='profil_user',
            name='solisgraph_json',
            field=models.JSONField(default=sav.models.json_solisgraph_default, verbose_name='json Solisgraph schema'),
        ),
    ]
