# Generated by Django 4.1 on 2023-10-13 11:56

import datetime
from django.db import migrations, models
import sav.models


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0042_profil_user_solisgraph_json_schema_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cl_herakles',
            name='CL',
            field=models.CharField(default='default', max_length=25, unique=True, verbose_name='CL'),
        ),
        migrations.AlterField(
            model_name='cl_herakles',
            name='date_last_update_information',
            field=models.DateField(default=datetime.datetime(2023, 10, 13, 11, 56, 56, 388963, tzinfo=datetime.timezone.utc), verbose_name='Date de dernière modif commentaire'),
        ),
        migrations.AlterField(
            model_name='client_herakles',
            name='Code_Client',
            field=models.CharField(help_text='Appuyer sur Ctrl pour sélectionner plusieurs Client', max_length=25, unique=True, verbose_name='Code Client'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 13, 13, 56, 56, 388963), help_text='Date et heure de événement', verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='profil_user',
            name='solisgraph_json',
            field=models.JSONField(default=sav.models.json_solisgraph_default, verbose_name='json Solisgraph chart'),
        ),
    ]
