# Generated by Django 4.1 on 2023-11-03 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0043_alter_cl_herakles_cl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='critere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critere', models.CharField(max_length=100, verbose_name='Critère')),
            ],
        ),
        migrations.AlterField(
            model_name='cl_herakles',
            name='date_last_update_information',
            field=models.DateField(default=datetime.datetime(2023, 11, 3, 10, 56, 18, 244537, tzinfo=datetime.timezone.utc), verbose_name='Date de dernière modif commentaire'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 11, 56, 18, 244537), help_text='Date et heure de événement', verbose_name='Date'),
        ),
    ]
