# Generated by Django 4.1 on 2023-11-03 11:13

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0044_critere_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cl_herakles',
            name='date_last_update_information',
            field=models.DateField(default=datetime.datetime(2023, 11, 3, 11, 13, 42, 138200, tzinfo=datetime.timezone.utc), verbose_name='Date de dernière modif commentaire'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 12, 13, 42, 122569), help_text='Date et heure de événement', verbose_name='Date'),
        ),
        migrations.CreateModel(
            name='evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2023, 11, 3, 11, 13, 42, 138200, tzinfo=datetime.timezone.utc), verbose_name="Date d'évaluation")),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('note', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Note')),
                ('critere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sav.critere')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_evaluation', to='sav.profil_user')),
            ],
        ),
    ]
