# Generated by Django 4.1 on 2023-11-03 11:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0045_alter_cl_herakles_date_last_update_information_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='critere',
            name='profil_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sav.profil_type', verbose_name='Type de profil'),
        ),
        migrations.AlterField(
            model_name='cl_herakles',
            name='date_last_update_information',
            field=models.DateField(default=datetime.datetime(2023, 11, 3, 11, 19, 42, 669605, tzinfo=datetime.timezone.utc), verbose_name='Date de dernière modif commentaire'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 3, 11, 19, 42, 669605, tzinfo=datetime.timezone.utc), verbose_name="Date d'évaluation"),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 12, 19, 42, 669605), help_text='Date et heure de événement', verbose_name='Date'),
        ),
    ]
