# Generated by Django 4.1 on 2023-11-03 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0046_critere_profil_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cl_herakles',
            name='date_last_update_information',
            field=models.DateField(default=datetime.datetime(2023, 11, 3, 11, 20, 3, 272987, tzinfo=datetime.timezone.utc), verbose_name='Date de dernière modif commentaire'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 3, 11, 20, 3, 272987, tzinfo=datetime.timezone.utc), verbose_name="Date d'évaluation"),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 12, 20, 3, 257365), help_text='Date et heure de événement', verbose_name='Date'),
        ),
    ]
