# Generated by Django 4.1 on 2024-01-30 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0049_alter_critere_options_alter_evaluation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noncompliance',
            name='numero',
            field=models.CharField(default='NC-', max_length=10, verbose_name='Numéro'),
        ),
        migrations.AlterField(
            model_name='cl_herakles',
            name='date_last_update_information',
            field=models.DateField(default=datetime.datetime(2024, 1, 30, 13, 14, 42, 755463, tzinfo=datetime.timezone.utc), verbose_name='Date de dernière modif commentaire'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 1, 30, 13, 14, 42, 756463, tzinfo=datetime.timezone.utc), verbose_name="Date d'évaluation"),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 30, 14, 14, 42, 750946), help_text='Date et heure de événement', verbose_name='Date'),
        ),
    ]
