# Generated by Django 4.1 on 2024-08-06 13:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sav", "0050_noncompliance_numero_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        default="L-", max_length=10, verbose_name="Numéro de lot"
                    ),
                ),
                (
                    "receptionDate",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de réception"
                    ),
                ),
                (
                    "article",
                    models.CharField(
                        default="MOD...",
                        max_length=10,
                        verbose_name="Référence article",
                    ),
                ),
            ],
            options={
                "ordering": ["-numero"],
            },
        ),
        migrations.CreateModel(
            name="tracability_organ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Description")),
            ],
        ),
        migrations.CreateModel(
            name="validationModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=100, verbose_name="Description")),
                (
                    "type",
                    models.IntegerField(
                        choices=[(0, "Montage"), (1, "Validation")],
                        default=0,
                        verbose_name="Type",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="cl_herakles",
            name="date_last_update_information",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 6, 13, 55, 46, 963748, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date de dernière modif commentaire",
            ),
        ),
        migrations.AlterField(
            model_name="evaluation",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 6, 13, 55, 46, 979406, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date d'évaluation",
            ),
        ),
        migrations.AlterField(
            model_name="evenement",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 6, 15, 55, 46, 963748),
                help_text="Date et heure de événement",
                verbose_name="Date",
            ),
        ),
        migrations.AlterField(
            model_name="noncompliance",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Attente retour marchandise défectueuse"),
                    (1, "En Expertise"),
                    (2, "Envoi chez le fournisseur pour expertise et suite"),
                    (3, "Clôturé"),
                ],
                default=0,
                verbose_name="Status",
            ),
        ),
        migrations.CreateModel(
            name="tracabiliy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "SN",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "CL",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="CL_tracability",
                        to="sav.cl_herakles",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batch",
                        to="sav.batch",
                    ),
                ),
                (
                    "organ",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracability_organ",
                        to="sav.tracability_organ",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Assembly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'évaluation"
                    ),
                ),
                (
                    "CL",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="CL_assembly",
                        to="sav.cl_herakles",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Monteur",
                    ),
                ),
                (
                    "validation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation",
                        to="sav.validationmodule",
                    ),
                ),
            ],
        ),
    ]
