# Generated by Django 4.1 on 2024-08-07 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sav", "0052_alter_cl_herakles_date_last_update_information_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="validationmodule",
            name="description",
            field=models.TextField(
                blank=True, max_length=200, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="cl_herakles",
            name="date_last_update_information",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 7, 8, 49, 13, 421659, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date de dernière modif commentaire",
            ),
        ),
        migrations.AlterField(
            model_name="evaluation",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 7, 8, 49, 13, 422655, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date d'évaluation",
            ),
        ),
        migrations.AlterField(
            model_name="evenement",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 7, 10, 49, 13, 416660),
                help_text="Date et heure de événement",
                verbose_name="Date",
            ),
        ),
        migrations.AlterField(
            model_name="validationmodule",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nom"),
        ),
    ]
