# Generated by Django 4.1 on 2024-08-13 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sav", "0054_alter_assembly_options_tracabiliy_location_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tracability_organ",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="batch",
            name="comment",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="Commentaire"
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="compliance",
            field=models.BooleanField(default=True, verbose_name="Conformité"),
        ),
        migrations.AddField(
            model_name="batch",
            name="soldout",
            field=models.BooleanField(default=False, verbose_name="Epuisé"),
        ),
        migrations.AlterField(
            model_name="cl_herakles",
            name="date_last_update_information",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 13, 12, 22, 58, 690205, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date de dernière modif commentaire",
            ),
        ),
        migrations.AlterField(
            model_name="evaluation",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 13, 12, 22, 58, 691224, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date d'évaluation",
            ),
        ),
        migrations.AlterField(
            model_name="evenement",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 13, 14, 22, 58, 685543),
                help_text="Date et heure de événement",
                verbose_name="Date",
            ),
        ),
        migrations.AlterField(
            model_name="tracabiliy",
            name="location",
            field=models.IntegerField(
                choices=[
                    (0, "Aucun"),
                    (1, "C1"),
                    (2, "C2"),
                    (3, "C3"),
                    (4, "C4"),
                    (5, "C5"),
                    (6, "C6"),
                    (7, "C7"),
                    (8, "Appoint"),
                    (9, "Tampon"),
                ],
                default=0,
                verbose_name="Emplacement",
            ),
        ),
    ]
