# Generated by Django 4.1 on 2024-08-14 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sav", "0055_alter_tracability_organ_options_batch_comment_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="tracabiliy",
            new_name="tracability",
        ),
        migrations.AlterField(
            model_name="cl_herakles",
            name="date_last_update_information",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 14, 7, 4, 28, 514170, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date de dernière modif commentaire",
            ),
        ),
        migrations.AlterField(
            model_name="evaluation",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 14, 7, 4, 28, 515179, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date d'évaluation",
            ),
        ),
        migrations.AlterField(
            model_name="evenement",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 14, 9, 4, 28, 510199),
                help_text="Date et heure de événement",
                verbose_name="Date",
            ),
        ),
    ]
