# Generated by Django 4.1 on 2024-09-27 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sav", "0058_alter_cause_solution_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cl_herakles",
            name="date_last_update_information",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 9, 27, 13, 38, 24, 72579, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date de dernière modif commentaire",
            ),
        ),
        migrations.AlterField(
            model_name="evaluation",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 9, 27, 13, 38, 24, 73580, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date d'évaluation",
            ),
        ),
        migrations.AlterField(
            model_name="evenement",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 9, 27, 15, 38, 24, 68238),
                help_text="Date et heure de événement",
                verbose_name="Date",
            ),
        ),
        migrations.AlterField(
            model_name="profil_user",
            name="idsa",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="id solisart"
            ),
        ),
    ]
